apply from: 'F:/Software/Ghidra/support/buildExtension.gradle'

// Fix jar name
jar {
	archiveBaseName = 'GhidraMCP'
}

tasks.named('buildExtension') {
	includeEmptyDirs = false
	eachFile { details ->
		String sourcePath = details.file.canonicalPath
		String buildPath = file('build').canonicalPath + File.separator
		if (details.file.name in ['nul', '_nul', 'gradle.properties', 'new_methods.txt', 'renovate.json'] || (!sourcePath.startsWith(buildPath) && (sourcePath.contains(File.separator + 'lib' + File.separator) || sourcePath.contains(File.separator + 'gradle' + File.separator) || sourcePath.contains(File.separator + '__pycache__' + File.separator) || sourcePath.contains(File.separator + 'temp_extract' + File.separator) || details.file.name.endsWith('.jar') || details.file.name.endsWith('.bak')))) details.exclude()
	}
}
